baseurl      = "https://blog.gitgud.sh"
title        = "Git Gud"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
rssLimit     = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." 

PygmentsCodeFences = true
PygmentsStyle = "monokai"


archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "parsec"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  defaultTheme = "dark"

  # Subtitle for home
  homeSubtitle = "A blog about my journey through tech, and the things I learn along the way."

  gitUrl = "https://github.com/parsec/blog/commit/"

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true
  
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My Blog!"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ] 

  # Social icons
[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/p4rsec_"

[[params.social]]
  name = "email"
  url  = "mailto:seth@beckman.sh"

[[params.social]]
  name = "github"
  url  = "https://github.com/parsec"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/sbeckman00/"

[[params.social]]
  name = "polywork"
  url  = "https://www.polywork.com/parsec" 

[taxonomies]
    category = "blog"
    series   = "series"
    tag      = "tags"

[languages]
  [languages.en]
    title = "Git Gud"
    subtitle = "A blog about my journey through tech, and the things I learn along the way."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    writtenBy = "Written by"
    readMore = "Read more"

    [languages.en.params.logo]
      logoMark     = ">"
      logoText     = "$ cd /blog.gitgud.sh/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]  
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume.pdf"  
