baseurl      = "https://blog.gitgud.sh/"
title        = "Git Gud"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "parsec"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A blog about my journey through tech, and the things I learn along the way."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My Blog!"
  keywords = "homepage, blog"
  images = [""]

  # Social icons
[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/p4rsec_"

[[params.social]]
  name = "email"
  url  = "mailto:p4rsec@pm.me"

[[params.social]]
  name = "github"
  url  = "https://github.com/parsec"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/sbeckman00/"

[[params.social]]
  name = "polywork"
  url  = "https://www.polywork.com/parsec" 

[taxonomies]
    category = "categories"
    series   = "series"
    tag      = "tags"

[languages]
  [languages.en]
    title = "Git Gud"
    subtitle = "A blog about my journey through tech, and the things I learn along the way."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    writtenBy = "Written by"
    readMore = "Read more"

    [languages.en.params.logo]
      logoText = "blog.gitgud.sh"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]  
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
